name: Apply On Merge

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  APPLICATION_NAME: fibonacci-app       # TODO: update to cluster name
  GKE_ZONE: northamerica-northeast1-a	  # TODO: update to cluster zone
  # DEPLOYMENT_NAME: gke-hello-app      # TODO: update deployment name if changed in deployment.yaml
  AR_REGION: northamerica-northeast1   # TODO: update to Artifact Registry repo region
  IMAGE_NAME: testjay

jobs:
  setup-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    # permissions:
    #   contents: 'read'
    #   id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker $AR_REGION-docker.pkg.dev --quiet

    - name: Build Docker Image
      run: |-
        docker build -t $IMAGE_NAME:latest ./client
        docker tag $IMAGE_NAME:latest $AR_REGION-docker.pkg.dev/$PROJECT_ID/$APPLICATION_NAME/$IMAGE_NAME:latest
        docker push $AR_REGION-docker.pkg.dev/$PROJECT_ID/$APPLICATION_NAME/$IMAGE_NAME:latest

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$APPLICATION_NAME" --zone "$GKE_ZONE"
    # - name: Deploy
    #   run: |-   #     kubectl apply -f deployment.yml
    #     kubectl rollout status deployment/$DEPLOYMENT_NAME
    #     kubectl get services -o wide